/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_00a119be (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/iixyfjipzvrfuzlxaneb/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2";

const deno: any = typeof Deno !== 'undefined' ? Deno : ((globalThis as any).Deno || { env: { get: (_: string) => undefined } });

// In development, the server may not have service-role credentials available.
// Provide a safe, in-memory fallback to avoid hard failures while clearly logging.
const memoryStore: Map<string, any> = new Map();
export const isMemoryFallback = !deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || !deno.env.get("SUPABASE_URL");

const client = () => createClient(
  deno.env.get("SUPABASE_URL") || "",
  deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "",
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  if (isMemoryFallback) {
    console.warn(`[kv_store] Using memory fallback. Not persisted. key=${key}`);
    memoryStore.set(key, value);
    return;
  }
  const supabase = client();
  const { error } = await supabase.from("kv_store_00a119be").upsert({ key, value });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  if (isMemoryFallback) {
    return memoryStore.get(key);
  }
  const supabase = client();
  const { data, error } = await supabase.from("kv_store_00a119be").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  if (isMemoryFallback) {
    memoryStore.delete(key);
    return;
  }
  const supabase = client();
  const { error } = await supabase.from("kv_store_00a119be").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Multi-set stores multiple key-value pairs in the database.
export const mset = async (entries: [string, any][]): Promise<void> => {
  if (isMemoryFallback) {
    entries.forEach(([key, value]) => memoryStore.set(key, value));
    return;
  }
  const supabase = client();
  const { error } = await supabase.from("kv_store_00a119be").upsert(entries.map(([key, value]) => ({ key, value })));
  if (error) {
    throw new Error(error.message);
  }
};

// Multi-get retrieves multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  if (isMemoryFallback) {
    return keys.map(k => memoryStore.get(k)).filter(v => typeof v !== 'undefined');
  }
  const supabase = client();
  const { data, error } = await supabase.from("kv_store_00a119be").select("key,value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data.map((row: { value: any }) => row.value);
};

// Multi-delete deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  if (isMemoryFallback) {
    keys.forEach(k => memoryStore.delete(k));
    return;
  }
  const supabase = client();
  const { error } = await supabase.from("kv_store_00a119be").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Get by prefix retrieves all key-value pairs with keys that start with the given prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  if (isMemoryFallback) {
    const results: any[] = [];
    memoryStore.forEach((value, key) => {
      if (key.startsWith(prefix)) {
        results.push(value);
      }
    });
    return results;
  }
  const supabase = client();
  const { data, error } = await supabase.from("kv_store_00a119be")
    .select("value")
    .like("key", `${prefix}%`);
  if (error) {
    throw new Error(error.message);
  }
  return data.map((row: { value: any }) => row.value);
};
